language: ruby
rvm:
  - 2.4.1
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'create database amazome_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
